package ingapplication;

import java.awt.Color;
import java.awt.Font;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableRowSorter;


public class AjoutClient extends javax.swing.JFrame {

    int pos = 0;
    /**
     * Creates new form AjoutClient
     */
    public AjoutClient() {
        initComponents();
        populateJtable();
        
        jTableClient.setShowGrid(true);
        jTableClient.setGridColor(Color.gray);
        
        JTableHeader th = jTableClient.getTableHeader();
       // th.setForeground(Color.blue);
        th.setFont(new Font("Tahoma", Font.BOLD, 12));
        this.setLocationRelativeTo(null);// center form in the screen
        
        jLabelDECONXION.setVisible(false);
        matricule.setVisible(false);
    }

/******************************************************************************************************/    
    
     public boolean varifData()
     {        
        if (NomC.getText().equals("") && NomC.getText().equals("")
                || PrenomC.getText().equals("")
                || adresse.getText().equals("")
                || numtel.getText().equals("")
                || Mail.getText().equals("")
                || ((JTextField)dateNais.getDateEditor().getUiComponent()).getText().equals("")
                || etatCivile.getText().equals("")){
            
            return false;
        }
        else if(dateNais.getDate().compareTo(new Date()) > 0){
            JOptionPane.showMessageDialog(null, "Vérifier la date de naissance ");
            return false;
        }
        else{
            return true;
        }   
    }
/******************************************************************************************************/    
    public boolean isUserNameExist(String un)
    {        
        boolean uExist= false;
        PreparedStatement st;
        ResultSet rs;

        String username = cinC.getText();

        String query = "SELECT * FROM `Client` WHERE `CIN` = ?";
        try {
            st = ConnectBD.connecterBD().prepareStatement(query);
        
            st.setString(1, username);         
            rs = st.executeQuery();
            
            if (rs.next())
            {               
                uExist = true;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        return uExist;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrenomP2 = new javax.swing.JTextField();
        PrenomP6 = new javax.swing.JTextField();
        mdp6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        mdp = new javax.swing.JLabel();
        cin = new javax.swing.JLabel();
        PrenomC = new javax.swing.JTextField();
        mdp2 = new javax.swing.JLabel();
        mdp3 = new javax.swing.JLabel();
        mdp4 = new javax.swing.JLabel();
        AjouterClient = new javax.swing.JButton();
        adresse = new javax.swing.JTextField();
        mdp5 = new javax.swing.JLabel();
        mdp7 = new javax.swing.JLabel();
        mdp8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        sexe = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        dateNais = new com.toedter.calendar.JDateChooser();
        mdp9 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableClient = new javax.swing.JTable();
        Modifier = new javax.swing.JButton();
        Mail = new javax.swing.JTextField();
        cinC = new javax.swing.JTextField();
        numtel = new javax.swing.JTextField();
        etatCivile = new javax.swing.JTextField();
        NomC = new javax.swing.JTextField();
        Supprimer = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelNomU = new javax.swing.JLabel();
        jLabelDECONXION = new javax.swing.JLabel();
        matricule = new javax.swing.JLabel();
        jLabelCompte = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        serch = new javax.swing.JTextField();

        PrenomP2.setBackground(new java.awt.Color(108, 122, 137));
        PrenomP2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        PrenomP2.setForeground(new java.awt.Color(228, 241, 254));

        PrenomP6.setBackground(new java.awt.Color(108, 122, 137));
        PrenomP6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        PrenomP6.setForeground(new java.awt.Color(228, 241, 254));

        mdp6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        mdp6.setForeground(new java.awt.Color(236, 240, 241));
        mdp6.setText("Vérifier mot de passe :");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("<<");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client");

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));

        mdp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mdp.setForeground(new java.awt.Color(236, 240, 241));
        mdp.setText("Nom");

        cin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cin.setForeground(new java.awt.Color(236, 240, 241));
        cin.setText("CIN");

        PrenomC.setBackground(new java.awt.Color(108, 122, 137));
        PrenomC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PrenomC.setForeground(new java.awt.Color(228, 241, 254));

        mdp2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mdp2.setForeground(new java.awt.Color(236, 240, 241));
        mdp2.setText("Adresse");

        mdp3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mdp3.setForeground(new java.awt.Color(236, 240, 241));
        mdp3.setText("Numero téléphone");

        mdp4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mdp4.setForeground(new java.awt.Color(236, 240, 241));
        mdp4.setText("Prénom");

        AjouterClient.setBackground(new java.awt.Color(38, 194, 129));
        AjouterClient.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AjouterClient.setForeground(new java.awt.Color(255, 255, 255));
        AjouterClient.setText("Ajouter");
        AjouterClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterClientActionPerformed(evt);
            }
        });

        adresse.setBackground(new java.awt.Color(108, 122, 137));
        adresse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adresse.setForeground(new java.awt.Color(228, 241, 254));

        mdp5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mdp5.setForeground(new java.awt.Color(236, 240, 241));
        mdp5.setText("Date naissance");

        mdp7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mdp7.setForeground(new java.awt.Color(236, 240, 241));
        mdp7.setText("Sexe");

        mdp8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mdp8.setForeground(new java.awt.Color(236, 240, 241));
        mdp8.setText("Etat civile");

        sexe.setBackground(new java.awt.Color(108, 122, 137));
        sexe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sexe.setForeground(new java.awt.Color(228, 241, 254));
        sexe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        dateNais.setBackground(new java.awt.Color(108, 122, 137));
        dateNais.setDateFormatString("dd-MM-yyyy");
        dateNais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        mdp9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mdp9.setForeground(new java.awt.Color(236, 240, 241));
        mdp9.setText("Mail");

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jTableClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableClient.setGridColor(new java.awt.Color(102, 102, 102));
        jTableClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableClient);

        Modifier.setBackground(new java.awt.Color(24, 167, 240));
        Modifier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Modifier.setForeground(new java.awt.Color(255, 255, 255));
        Modifier.setText("Modifier");
        Modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierActionPerformed(evt);
            }
        });

        Mail.setBackground(new java.awt.Color(108, 122, 137));
        Mail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Mail.setForeground(new java.awt.Color(228, 241, 254));

        cinC.setBackground(new java.awt.Color(108, 122, 137));
        cinC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cinC.setForeground(new java.awt.Color(228, 241, 254));

        numtel.setBackground(new java.awt.Color(108, 122, 137));
        numtel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numtel.setForeground(new java.awt.Color(228, 241, 254));

        etatCivile.setBackground(new java.awt.Color(108, 122, 137));
        etatCivile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        etatCivile.setForeground(new java.awt.Color(228, 241, 254));

        NomC.setBackground(new java.awt.Color(108, 122, 137));
        NomC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NomC.setForeground(new java.awt.Color(228, 241, 254));

        Supprimer.setBackground(new java.awt.Color(242, 38, 19));
        Supprimer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Supprimer.setForeground(new java.awt.Color(255, 255, 255));
        Supprimer.setText("Supprimer");
        Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(248, 148, 6));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });

        jLabelNomU.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNomU.setForeground(new java.awt.Color(253, 227, 167));
        jLabelNomU.setText("Nom Utilisateur");
        jLabelNomU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelNomUMouseEntered(evt);
            }
        });

        jLabelDECONXION.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDECONXION.setForeground(new java.awt.Color(236, 240, 241));
        jLabelDECONXION.setText("Déconnexion");
        jLabelDECONXION.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDECONXIONMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelDECONXIONMouseEntered(evt);
            }
        });

        matricule.setForeground(new java.awt.Color(255, 255, 255));
        matricule.setText("matricule");

        jLabelCompte.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelCompte.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCompte.setText("Comptes");
        jLabelCompte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCompte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCompteMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Clients");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Personnels");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNomU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDECONXION)
                .addGap(379, 379, 379)
                .addComponent(matricule)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabelCompte)
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabelCompte))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelNomU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelDECONXION)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(matricule)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        serch.setBackground(new java.awt.Color(44, 62, 80));
        serch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        serch.setForeground(new java.awt.Color(255, 255, 255));
        serch.setText("Cliquez ici pour rechercher ...");
        serch.setToolTipText("");
        serch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        serch.setOpaque(false);
        serch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serchMouseClicked(evt);
            }
        });
        serch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                serchKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(Supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(AjouterClient, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cin)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mdp)
                                    .addComponent(mdp4)
                                    .addComponent(PrenomC, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                    .addComponent(cinC, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NomC, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGap(22, 22, 22)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(mdp2)
                                .addComponent(adresse, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                .addComponent(mdp3)
                                .addComponent(mdp9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Mail)
                                .addComponent(numtel, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(18, 18, Short.MAX_VALUE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mdp5)
                                .addComponent(mdp7)
                                .addComponent(mdp8)
                                .addComponent(etatCivile)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(sexe, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dateNais, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(serch, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(mdp2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(mdp5)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(dateNais, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Modifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(AjouterClient)
                                            .addComponent(Supprimer))
                                        .addGap(40, 40, 40))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(mdp9)
                                                .addGap(13, 13, 13)
                                                .addComponent(Mail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addComponent(mdp3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(numtel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(72, 72, 72))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(cinC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(mdp)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(NomC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(mdp4)
                                                .addGap(13, 13, 13)
                                                .addComponent(PrenomC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(73, 73, 73)))
                                        .addComponent(serch, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(mdp7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sexe, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(mdp8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(etatCivile, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(107, 107, 107)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cin))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AjouterClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterClientActionPerformed

        if (varifData()){
                       
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
            String theDate = dateFormat.format(dateNais.getDate());
            
            
            String cin = cinC.getText();
            String nomC = NomC.getText();
            String prenomc = PrenomC.getText();
            String adressec = adresse.getText();                
            String sexe = this.sexe.getSelectedItem().toString();
            String etatcivile = etatCivile.getText();
            String datenais = theDate;
            String numtel = this.numtel.getText();
            String mail = Mail.getText();
            

            if (isUserNameExist(cin))
                {
                    JOptionPane.showMessageDialog(null, "Client déja existe ");
                }else{
                    Client client = new Client(cin, nomC, prenomc, adressec, numtel, datenais, sexe, etatcivile, mail);
                    ClientQuery cq = new ClientQuery();
                     
                    boolean b =  cq.insertClient(client);
//                    refreshJtable();     
//                    clearFields();        
                    if (b){
                        Accueil form = new Accueil();

                        form.CINCOMP.setSelectedItem(cin);
                        form.NomPrenom.setText(nomC+" "+prenomc);
                        
                        form.setVisible(true);
                        form.pack();
                        form.setLocationRelativeTo(null);
                        // close the current form
                        form.jLabelNomU.setText(this.jLabelNomU.getText());
                        form.matricule.setText(this.matricule.getText());
                        this.dispose();
                    }                    
                }
        }else{
            JOptionPane.showMessageDialog(null, "Remplir tout les champs ");
        }
    }//GEN-LAST:event_AjouterClientActionPerformed

/******************************************************************************************************/    
    
    public void populateJtable(){
     
        ClientQuery cq = new ClientQuery();
        ArrayList<Client> clList = cq.clientList();
        String[] colNames = {"CIN","Nom","Prenom","Adresse","Sexe","Etat civile","Date Naissance","Numero","Mail"};
        Object[][] rows = new Object[clList.size()][9];
        
        for (int i =0; i< clList.size(); i++){
            rows[i][0] = clList.get(i).getCin();
            rows[i][1] = clList.get(i).getNomc();
            rows[i][2] = clList.get(i).getPrenom();
            rows[i][3] = clList.get(i).getAdresse();
            rows[i][4] = clList.get(i).getSexe();
            rows[i][5] = clList.get(i).getEtatCivile();
            rows[i][6] = clList.get(i).getDateNais();
            rows[i][7] = clList.get(i).getNumeroTel();
            rows[i][8] = clList.get(i).getMail();
        }
        MyModelClient mmc = new MyModelClient(rows,colNames);
        jTableClient.setModel(mmc);
        jTableClient.setRowHeight(40);
        jTableClient.getColumnModel().getColumn(8).setPreferredWidth(120);       
    } 
    
/******************************************************************************************************/    
    public void refreshJtable(){
        jTableClient.setModel(new DefaultTableModel());
        populateJtable();
    }
/******************************************************************************************************/    
    public void clearFields(){
        
        cinC.setText("");
        NomC.setText("");
        PrenomC.setText("");
        adresse.setText("");
        Mail.setText("");
        this.dateNais.setDate(null);
        numtel.setText("");
        etatCivile.setText("");
    }
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTableClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientMouseClicked

         SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        //display selected JTable row data
        //get selected row index
        int rowIndex = jTableClient.getSelectedRow();

        cinC.setText((jTableClient.getValueAt(rowIndex, 0)).toString());
        NomC.setText((jTableClient.getValueAt(rowIndex, 1)).toString());
        
        PrenomC.setText((jTableClient.getValueAt(rowIndex, 2)).toString());
        adresse.setText((jTableClient.getValueAt(rowIndex, 3)).toString());
        sexe.setSelectedItem((jTableClient.getValueAt(rowIndex, 4)).toString());
        etatCivile.setText((jTableClient.getValueAt(rowIndex, 5)).toString());
        
        try {
            this.dateNais.setDate(sdf.parse((jTableClient.getValueAt(rowIndex, 6)).toString()));
        } catch (ParseException ex) {
            Logger.getLogger(AjoutClient.class.getName()).log(Level.SEVERE, null, ex);
        }
        //new SimpleDateFormat("dd-MM-yyyy").parse((String)jTable1.getValueAt(rowIndex, 6).toString());
        numtel.setText((jTableClient.getValueAt(rowIndex, 7)).toString());
        Mail.setText((jTableClient.getValueAt(rowIndex, 8)).toString());

    }//GEN-LAST:event_jTableClientMouseClicked

    private void ModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierActionPerformed
        
        if (varifData()){

            String cin = cinC.getText();
            String nomC = NomC.getText();
            String prenomc = PrenomC.getText();
            String adressec = adresse.getText();
            String sexe = this.sexe.getSelectedItem().toString();
            String etatcivile = etatCivile.getText();
            String datenais = ((JTextField)dateNais.getDateEditor().getUiComponent()).getText();
            String numtel = this.numtel.getText();
            String mail = Mail.getText();

            if (!isUserNameExist(cinC.getText()))
            {
                JOptionPane.showMessageDialog(null, "Client n'existe pas !");
            }else{
                
                Client client = new Client(cin, nomC, prenomc, adressec, numtel, datenais, sexe, etatcivile, mail);
                ClientQuery cq = new ClientQuery();

                boolean b =  cq.updateClient(client);
                refreshJtable();     
                clearFields();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Sélectionnez un client dans la table  ");
        }
    }//GEN-LAST:event_ModifierActionPerformed

    
    
    private void SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerActionPerformed
     
        String y ="voulez vous supprimé le client "+NomC.getText()+" "+PrenomC.getText();
        int yesOrNo = JOptionPane.showConfirmDialog(null, y ,"Suppression du client",JOptionPane.OK_CANCEL_OPTION, 0 );
        
        if (yesOrNo == 0){
             String cin = cinC.getText();
             if (!cin.equals("")){
                 ClientQuery cp = new ClientQuery();
                 boolean x = cp.deleteClient(cin);
                 refreshJtable();     
                 clearFields();
             }else{
                 JOptionPane.showMessageDialog(null, "Sélectionnez un client dans la table ");
             }
        }
    }//GEN-LAST:event_SupprimerActionPerformed

/*************************************************************************************************************/
    private void showData(int index){
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        //get selected row index
        cinC.setText((jTableClient.getValueAt(index, 0)).toString());
        NomC.setText((jTableClient.getValueAt(index, 1)).toString());
        
        PrenomC.setText((jTableClient.getValueAt(index, 2)).toString());
        adresse.setText((jTableClient.getValueAt(index, 3)).toString());
        sexe.setSelectedItem((jTableClient.getValueAt(index, 4)).toString());
        etatCivile.setText((jTableClient.getValueAt(index, 5)).toString());
        
        try {
            this.dateNais.setDate(sdf.parse((jTableClient.getValueAt(index, 6)).toString()));
        } catch (ParseException ex) {
            Logger.getLogger(AjoutClient.class.getName()).log(Level.SEVERE, null, ex);
        }
        //new SimpleDateFormat("dd-MM-yyyy").parse((String)jTable1.getValueAt(rowIndex, 6).toString());
        numtel.setText((jTableClient.getValueAt(index, 7)).toString());
        Mail.setText((jTableClient.getValueAt(index, 8)).toString());        
        
    }  
    
    private void jLabelDECONXIONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDECONXIONMouseClicked
        //show a new form
        Login form = new Login();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_jLabelDECONXIONMouseClicked

    private void jLabelDECONXIONMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDECONXIONMouseEntered
        jLabelDECONXION.setVisible(true);
    }//GEN-LAST:event_jLabelDECONXIONMouseEntered

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
        jLabelDECONXION.setVisible(false);
    }//GEN-LAST:event_jPanel2MouseExited

    private void jLabelNomUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNomUMouseEntered
        jLabelDECONXION.setVisible(true);
    }//GEN-LAST:event_jLabelNomUMouseEntered

    private void jLabelCompteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCompteMouseClicked
        //show a new form
        Accueil form = new Accueil();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);

        form.jLabelNomU.setText(this.jLabelNomU.getText());
        this.dispose();
    }//GEN-LAST:event_jLabelCompteMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        //show a new form
        AjoutClient form = new AjoutClient();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);

        form.jLabelNomU.setText(this.jLabelNomU.getText());
        form.matricule.setText(this.matricule.getText());
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        //show a new form
        PersonnetForm form = new PersonnetForm();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);

        form.jLabelNomU.setText(this.jLabelNomU.getText());
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void serchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serchMouseClicked
        serch.setText("");
    }//GEN-LAST:event_serchMouseClicked

    private void serchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serchKeyTyped

        MyModelClient model = (MyModelClient) jTableClient.getModel();
        String search = serch.getText().toLowerCase();
        TableRowSorter<MyModelClient> tr = new TableRowSorter<MyModelClient>(model);
        jTableClient.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));

    }//GEN-LAST:event_serchKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjoutClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjouterClient;
    private javax.swing.JTextField Mail;
    private javax.swing.JButton Modifier;
    private javax.swing.JTextField NomC;
    private javax.swing.JTextField PrenomC;
    private javax.swing.JTextField PrenomP2;
    private javax.swing.JTextField PrenomP6;
    private javax.swing.JButton Supprimer;
    private javax.swing.JTextField adresse;
    private javax.swing.JLabel cin;
    private javax.swing.JTextField cinC;
    private com.toedter.calendar.JDateChooser dateNais;
    private javax.swing.JTextField etatCivile;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCompte;
    private javax.swing.JLabel jLabelDECONXION;
    public javax.swing.JLabel jLabelNomU;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableClient;
    public static javax.swing.JLabel matricule;
    private javax.swing.JLabel mdp;
    private javax.swing.JLabel mdp2;
    private javax.swing.JLabel mdp3;
    private javax.swing.JLabel mdp4;
    private javax.swing.JLabel mdp5;
    private javax.swing.JLabel mdp6;
    private javax.swing.JLabel mdp7;
    private javax.swing.JLabel mdp8;
    private javax.swing.JLabel mdp9;
    private javax.swing.JTextField numtel;
    private javax.swing.JTextField serch;
    private javax.swing.JComboBox<String> sexe;
    // End of variables declaration//GEN-END:variables
}
